##### 写入导入 numpy 的语句，并且给 numpy 命名为 np。

In [1]:
import numpy as np

##### 创建一个变量名为 arrl 的一维数组 里面的元素为整数 6、2、-7、2、1。 创建后输出 arr1. 

In [2]:
arr1 = np.array([6, 2, -7, 2, 8, -2, 1])
arr1

array([ 6,  2, -7,  2,  8, -2,  1])

##### 创建一个变量名为 arr2 的二维数组， 里面的元素为以下两个数组： 由整数 1、3、5、 组成的一维数组，以及由整数 2、 4、 6 组成的一维数组创建后输出 arr2。

In [3]:
arr2 = np.array([[1, 3, 5],[2, 4, 6]])
arr2

array([[1, 3, 5],
       [2, 4, 6]])

##### 分别打印 arr1 和 arr2 的维度、形状、元素数量、元素类型。

In [7]:
print(arr1. ndim)
print(arr2. ndim)
print(arr1. shape)
print(arr2. shape)
print(arr1. size)
print(arr2. size)
print(arr1. dtype)
print(arr2. dtype)

1
2
(7,)
(2, 3)
7
6
int64
int64


##### 创建一个变量名为 arr_all_0 的一维数组里面的元素为 6 个 0, 并输出。

In [9]:
arr_all_0 = np. zeros(6)
arr_all_0

array([0., 0., 0., 0., 0., 0.])

##### 创建一个变量名为 arr_all_1 的一维数组里面的元素为 6 个 1, 并输出。

In [10]:
arr_all_1 = np. ones(6)
arr_all_1

array([1., 1., 1., 1., 1., 1.])

##### 创建一个变量名为 arr_even 的一维数组 里面的元素为 10 (包括 10) 到 20 (包括 20) 之间的偶数，并输出。

In [11]:
arr_even = np.arange(10, 21, 2)
arr_even

array([10, 12, 14, 16, 18, 20])

#####

#####

#####

#####