##### 连接数组

In [2]:
import numpy as np

arr1 = np.array([5, 17, 3, 26, 31])
arr2 = np.zeros(2)
arr3 = np.ones(3)
np.concatenate([arr1, arr2, arr3])

array([ 5., 17.,  3., 26., 31.,  0.,  0.,  1.,  1.,  1.])

##### sorted 函数

In [4]:
list1 = [5, 17, 3, 26, 31]
sorted_list1 = sorted(list1)
print(sorted_list1)
print(list1)

[3, 5, 17, 26, 31]
[5, 17, 3, 26, 31]


##### sorted 函数

In [5]:
list2 = [5, 17, 3, 26, 31]
list1. sort()
print(list1)

[3, 5, 17, 26, 31]


##### Numpy 的 sort 函数

In [6]:
import numpy as np
arr1 = np.array([5, 17, 3, 26, 31])
print(np.sort(arr1)) # 不改变arr1
print(arr1)

[ 3  5 17 26 31]
[ 5 17  3 26 31]


##### Numpy 的 sort 方法

In [7]:
import numpy as np
arr2 = np.array([5, 17, 3, 26, 31])
print(arr2.sort()) # 什么都不返回
print(arr2)

None
[ 3  5 17 26 31]


##### 用索引获得元素

In [2]:
import numpy as np
arr3 = np.array([3, 5, 17, 26, 31])
print(arr3[0])
print(arr3[-2])

3
26


##### 用索引获得部分数组

In [3]:
import numpy as np
arr4 = np.array([3, 5, 17, 26, 31])
print(arr4[1:4])

[ 5 17 26]


##### 数组和数组的运算

In [7]:
import numpy as np
arr5 = np.array([6, 7, 8, 9, 10])
arr6 = np.array([1, 1, 1, 1, 1])
print(arr5 + arr6)
print(arr5 - arr6)
print(arr5 * arr6)
print(arr5 / arr6)
print(arr5 * 3)

[ 7  8  9 10 11]
[5 6 7 8 9]
[ 6  7  8  9 10]
[ 6.  7.  8.  9. 10.]
[18 21 24 27 30]


##### 数组和数字的运算

In [10]:
import numpy as np
arr7 = np.array([6, 7, 8, 9, 10])
print(arr7. max())
print(arr7. min())
print(arr7. sum())
print(arr7. mean())

10
6
40
8.0


##### 根据条件筛选数组元素

In [11]:
import numpy as np
arr8 = np.array([-22, 3, 65, 9, 11, 7])
print(arr8[arr8 > 6])

[65  9 11  7]


##### 根据条件筛选数组元素

In [12]:
import numpy as np
arr9 = np.array([-22, 3, 65, 9, 11, 7])
print(arr9[(arr9 > 6) & (arr9 < 10)])

[9 7]
