写入导入 numpy 的语句，并且给 numpy 别名为 np。

In [1]:
import numpy as np

创建 arr1 为包含了元素1、 3、 2、 4、 9 的数组， 创建 arr2 为长度为 5 的由 1 组成的一维数组， arr3 为长度为 3 的由 0 组成的一维数组。

In [2]:
arr1 = np. array([1, 3, 2, 4, 9])
arr2 = np. ones(5)
arr3 = np. zeros(3)

创建数组 arr4, 包括所有 arr1、 arr2、 arr3 里面的数字，并输出。

In [5]:
arr4 =  np. concatenate([arr1, arr2, arr3])
arr4

array([1., 3., 2., 4., 9., 1., 1., 1., 1., 1., 0., 0., 0.])

更改 arr1, 对 arr1 里的元素进行排序， 并输出排序后的结果。

In [6]:
arr1. sort()
arr1

array([1, 2, 3, 4, 9])

用两种方法打印 arr1 的第三个元素。

In [7]:
print(arr1[2])
print(arr1[-3])

3
3


输出从 arr1 第 2 个元素到第 4 个元素组成的数组。

In [8]:
arr1[1:4]

array([2, 3, 4])

输出 arr1 与 arr2 的同位置元素相加后组成的数组。

In [9]:
arr1 + arr2

array([ 2.,  3.,  4.,  5., 10.])

输出 arr1 的各个元素乘以 -5 后组成的数组。

In [10]:
arr1 * -5

array([ -5, -10, -15, -20, -45])

打印 arr1 数组的最大值、 最小值、 和、 平均值。

In [11]:
print(arr1.max())
print(arr1.min())
print(arr1.sum())
print(arr1.mean())

9
1
19
3.8


筛选出 arr1 数组里所有小于 1 或大于 3 的数字， 并打印出来

In [13]:
arr1[(arr1 < 1)|(arr1 > 3)]

array([4, 9])